name       : baobab
version    : 3.28.0
release    : 13
source     :
    - https://download.gnome.org/sources/baobab/3.28/baobab-3.28.0.tar.xz : 530bb269e19d1f9f562fab90377eda8ce3c3efd521e4d569f7c40e56fa3e5d63
license    : GPL-2.0-only
component  : desktop.gnome
summary    : A graphical directory tree analyzer
description: |
    A graphical directory tree analyzer
builddeps  :
    - pkgconfig(gtk+-3.0)
    - itstool
    - vala
setup      : |
    %patch -p1 < $pkgfiles/0001-Stop-registering-mimetype-to-open-directories.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
