name       : baobab
version    : 3.26.1
release    : 12
source     :
    - https://download.gnome.org/sources/baobab/3.26/baobab-3.26.1.tar.xz : 7a59ab5945f5d90725231b10d85a1893403f56660b1627c111d2b4eeb1ef787e
license    : GPL-2
component  : desktop.gnome
summary    : A graphical directory tree analyzer
description: |
    A graphical directory tree analyzer
builddeps  :
    - pkgconfig(gtk+-3.0)
    - itstool
setup      : |
    %patch -p1 < $pkgfiles/0001-Stop-registering-mimetype-to-open-directories.patch
    %configure
build      : |
    %make
install    : |
    %make_install
