name       : baobab
version    : 3.18.1
release    : 7
source     :
    - http://ftp.gnome.org/pub/GNOME/sources/baobab/3.18/baobab-3.18.1.tar.xz : c2ac90426390e77147446a290c1480c49936c0a224f740b555ddaec2675b44b5
license    : GPL-2
builddeps  :
    - itstool
    - pkgconfig(gtk+-3.0)
summary    : A graphical directory tree analyzer
description: |
    A graphical directory tree analyzer
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
