name       : baobab
version    : '42.0'
release    : 22
source     :
    - https://download.gnome.org/sources/baobab/42/baobab-42.0.tar.xz : 4b1aabe6bab1582b3fea79a2829bce7f2415bb6e5062f25357aeedd5317a50dc
license    : GPL-2.0-only
component  : desktop.gnome
summary    : A graphical directory tree analyzer
description: |
    A graphical directory tree analyzer
builddeps  :
    - pkgconfig(gtk4)
    - pkgconfig(libadwaita-1)
    - itstool
    - vala
setup      : |
    %patch -p1 < $pkgfiles/0001-Stop-registering-mimetype-to-open-directories.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
