name       : baobab
version    : 3.34.0
release    : 16
source     :
    - https://download.gnome.org/sources/baobab/3.34/baobab-3.34.0.tar.xz : 46ebd9466da6a68c340653e9095f1e905b6fac79305879a9e644634f7da98607
license    : GPL-2.0-only
component  : desktop.gnome
summary    : A graphical directory tree analyzer
description: |
    A graphical directory tree analyzer
builddeps  :
    - pkgconfig(gtk+-3.0)
    - itstool
    - vala
setup      : |
    %patch -p1 < $pkgfiles/0001-Stop-registering-mimetype-to-open-directories.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
