name       : baobab
version    : '44.0'
release    : 25
source     :
    - https://download.gnome.org/sources/baobab/44/baobab-44.0.tar.xz : 845b63bb9123d74568c8126c571bbc74273483ff920179a2cf1eddbbefa1bfc0
license    : GPL-2.0-only
component  : desktop.gnome
summary    : A graphical directory tree analyzer
description: |
    A graphical directory tree analyzer
builddeps  :
    - pkgconfig(gtk4)
    - pkgconfig(libadwaita-1)
    - desktop-file-utils
    - itstool
    - vala
setup      : |
    %patch -p1 < $pkgfiles/0001-Stop-registering-mimetype-to-open-directories.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
