name       : baobab
version    : 3.38.0
release    : 18
source     :
    - https://download.gnome.org/sources/baobab/3.38/baobab-3.38.0.tar.xz : 048468147860816b97f15d50b3c84e9acf0539c1441cfeb63703d112e8728329
license    : GPL-2.0-only
component  : desktop.gnome
summary    : A graphical directory tree analyzer
description: |
    A graphical directory tree analyzer
builddeps  :
    - pkgconfig(gtk+-3.0)
    - itstool
    - vala
setup      : |
    %patch -p1 < $pkgfiles/0001-Stop-registering-mimetype-to-open-directories.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
