name       : baobab
version    : 3.22.1
release    : 10
source     :
    - http://ftp.gnome.org/pub/GNOME/sources/baobab/3.22/baobab-3.22.1.tar.xz : 5bebcb1797888503d75c9985404e534940c211ffc37e5c7de09eed058dfc97ff
license    : GPL-2
component  : desktop.gnome
builddeps  :
    - itstool
    - pkgconfig(gtk+-3.0)
summary    : A graphical directory tree analyzer
description: |
    A graphical directory tree analyzer
setup      : |
    %patch -p1 < $pkgfiles/0001-Stop-registering-mimetype-to-open-directories.patch
    %configure
build      : |
    %make
install    : |
    %make_install
